### PR TITLE
Database performance audit

### PR DESCRIPTION
**Pull request by carreraprogrammer**
Captura desde 2023-06-14 15-25-57

This branch was created in order to improve the performance of some queries. To do this we followed the following steps:

- [x] The following queries are taking too much time (1 sec = 1000ms can be considered as too much time for database query). Try them on your machine to confirm it:

- SELECT COUNT(*) FROM visits where animal_id = 4;

- SELECT * FROM visits where vet_id = 2;

- SELECT * FROM owners where email = 'owner_18327@mail.com';

- Use EXPLAIN ANALYZE on the previous queries to check what is happening. Take screenshots of them - they will be necessary later.

- [x] Find a way to decrease the execution time of the first query. Look for hints in the previous lessons.

- [x] Find a way to improve execution time of the other two queries.

- [x] While you are making changes, check if they help by running EXPLAIN ANALYZE. Once you succeed, take a screenshot of the EXPLAIN ANALYZE result showing that time actually decreased.

- [x] Any changes you made to your database schema should be added to the schema.sql file and commited in a new pull request.

- [x] If you decide to commit any INSERT INTO queries - remember to add the to the data.sql file. It is important to keep only the queries that change the database structure in the schema.sql file.

- [x] In your pull request description include screenshots with EXPLAIN ANALYZE results (before and after you improve the speed) for each of the 3 problematic queries.

**FIRST QUERY**

_First performance_

Analyze_query_1

_Improved performance_

Improve_query_1
ance_

**SECOND QUERY**

_First perform

Analyze_query_2

_Improved performance_

Improve_query_2

**THIRD QUERY**

_First performance_

Analyze_query_3

_Improved performance_

Improve_query_3

### CODE REVIEW

**Review by Davidosky007 — COMMENTED** [review]
Hi @carreraprogrammer 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't show contributions from your partners as this is a paired programming activity 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by addod19** [comment]
### Hi @carreraprogrammer, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the README file is not professional, it is lacking relevant headers like the `key features`, `future features` etc. Take a look at the [template](https://github.com/microverseinc/readme-template) for reference

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by amon-cofie — APPROVED** [review]
Hi @carreraprogrammer , 👋 

Your project is complete and very impressive 💯!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

🚀 You have a descriptive pull request summary
🚀 You have a professional Readme file
🚀 You have good commit messages
🚀 You used Gitflow properly


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by carreraprogrammer** [comment]
Hello @amon-cofie !!

Thank you very much for the review, I'll merge it 😁🎉🎊

**Pull request merged**
